/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ATTENUATEDCRYSTALBALLLOWHIGH
#define ATTENUATEDCRYSTALBALLLOWHIGH

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooAttenuatedCrystalBallLowHigh : public RooAbsPdf {
 public:
  RooAttenuatedCrystalBallLowHigh() {} ; 
  RooAttenuatedCrystalBallLowHigh(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _mu,
	      RooAbsReal& _kT,
	      RooAbsReal& _mean,
	      RooAbsReal& _sigma,
	      RooAbsReal& _alpha,
	      RooAbsReal& _n,
	      RooAbsReal& _alpha2,
	      RooAbsReal& _n2);
  RooAttenuatedCrystalBallLowHigh(const RooAttenuatedCrystalBallLowHigh& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooAttenuatedCrystalBallLowHigh(*this,newname); }
  inline virtual ~RooAttenuatedCrystalBallLowHigh() { }

 protected:

  RooRealProxy x ;
  RooRealProxy mu ;
  RooRealProxy kT ;
  RooRealProxy mean ;
  RooRealProxy sigma ;
  RooRealProxy alpha ;
  RooRealProxy n ;
  RooRealProxy alpha2 ;
  RooRealProxy n2 ;
  
  Double_t evaluate() const ;

 private:

  ClassDef(RooAttenuatedCrystalBallLowHigh,1)
};
 
#endif
