/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOGAUSSWITHSKIRT
#define ROOGAUSSWITHSKIRT

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooGaussWithSkirt : public RooAbsPdf {
public:
  RooGaussWithSkirt() {} ; 
  RooGaussWithSkirt(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _norma,
	      RooAbsReal& _mean,
	      RooAbsReal& _sigma,
	      RooAbsReal& _alphaL,
	      RooAbsReal& _alphaR);
  RooGaussWithSkirt(const RooGaussWithSkirt& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooGaussWithSkirt(*this,newname); }
  inline virtual ~RooGaussWithSkirt() { }

protected:

  RooRealProxy x ;
  RooRealProxy norma ;
  RooRealProxy mean ;
  RooRealProxy sigma ;
  RooRealProxy alphaL ;
  RooRealProxy alphaR ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooGaussWithSkirt,1) // Your description goes here...
};
 
#endif
