/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef SUPERCRYSTALBALL
#define SUPERCRYSTALBALL

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooSuperCrystalBall : public RooAbsPdf {
 public:
  RooSuperCrystalBall() {} ; 
  RooSuperCrystalBall(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _mean,
	      RooAbsReal& _sigma,
	      RooAbsReal& _alpha,
	      RooAbsReal& _n,
	      RooAbsReal& _alpha2,
	      RooAbsReal& _n2);
  RooSuperCrystalBall(const RooSuperCrystalBall& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooSuperCrystalBall(*this,newname); }
  inline virtual ~RooSuperCrystalBall() { }

 protected:

  RooRealProxy x ;
  RooRealProxy mean ;
  RooRealProxy sigma ;
  RooRealProxy alpha ;
  RooRealProxy n ;
  RooRealProxy alpha2 ;
  RooRealProxy n2 ;
  
  Double_t evaluate() const ;

 private:

  ClassDef(RooSuperCrystalBall,1)
};
 
#endif
