/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef SUPERCRYSTALBALL
#define SUPERCRYSTALBALL

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class SuperCrystalBall : public RooAbsPdf {
public:
  SuperCrystalBall() {} ; 
  SuperCrystalBall(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _norma,
	      RooAbsReal& _mean,
	      RooAbsReal& _sigma,
	      RooAbsReal& _alpha,
	      RooAbsReal& _n,
	      RooAbsReal& _alpha2,
	      RooAbsReal& _n2);
  SuperCrystalBall(const SuperCrystalBall& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new SuperCrystalBall(*this,newname); }
  inline virtual ~SuperCrystalBall() { }

protected:

  RooRealProxy x ;
  RooRealProxy norma ;
  RooRealProxy mean ;
  RooRealProxy sigma ;
  RooRealProxy alpha ;
  RooRealProxy n ;
  RooRealProxy alpha2 ;
  RooRealProxy n2 ;
  
  Double_t evaluate() const ;

private:

  ClassDef(SuperCrystalBall,1) // Your description goes here...
};
 
#endif
