echo "qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_1 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_1/bjob_1.sh"

qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_1 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_1/bjob_1.sh

echo "qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_2 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_2/bjob_2.sh"

qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_2 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_2/bjob_2.sh

echo "qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_3 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_3/bjob_3.sh"

qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_3 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_3/bjob_3.sh

echo "qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_4 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_4/bjob_4.sh"

qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_4 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_4/bjob_4.sh

echo "qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_5 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_5/bjob_5.sh"

qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_5 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_5/bjob_5.sh

echo "qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_6 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_6/bjob_6.sh"

qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_6 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_6/bjob_6.sh

echo "qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_7 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_7/bjob_7.sh"

qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_7 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_7/bjob_7.sh

echo "qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_8 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_8/bjob_8.sh"

qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_8 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_8/bjob_8.sh

echo "qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_9 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_9/bjob_9.sh"

qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_9 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_9/bjob_9.sh

echo "qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_10 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_10/bjob_10.sh"

qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_10 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_10/bjob_10.sh

echo "qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_11 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_11/bjob_11.sh"

qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_11 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_11/bjob_11.sh

echo "qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_12 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_12/bjob_12.sh"

qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_12 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_12/bjob_12.sh

echo "qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_13 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_13/bjob_13.sh"

qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_13 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_13/bjob_13.sh

echo "qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_14 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_14/bjob_14.sh"

qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_14 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_14/bjob_14.sh

echo "qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_15 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_15/bjob_15.sh"

qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_15 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_15/bjob_15.sh

echo "qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_16 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_16/bjob_16.sh"

qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_16 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_16/bjob_16.sh

echo "qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_17 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_17/bjob_17.sh"

qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_17 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_17/bjob_17.sh

echo "qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_18 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_18/bjob_18.sh"

qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_18 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_18/bjob_18.sh

echo "qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_19 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_19/bjob_19.sh"

qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_19 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_19/bjob_19.sh

echo "qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_20 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_20/bjob_20.sh"

qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_20 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_20/bjob_20.sh

echo "qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_21 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_21/bjob_21.sh"

qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_21 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_21/bjob_21.sh

echo "qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_22 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_22/bjob_22.sh"

qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_22 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_22/bjob_22.sh

echo "qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_23 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_23/bjob_23.sh"

qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_23 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_23/bjob_23.sh

echo "qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_24 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_24/bjob_24.sh"

qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_24 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_24/bjob_24.sh

echo "qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_25 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_25/bjob_25.sh"

qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_25 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_25/bjob_25.sh

echo "qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_26 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_26/bjob_26.sh"

qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_26 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_26/bjob_26.sh

echo "qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_27 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_27/bjob_27.sh"

qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_27 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_27/bjob_27.sh

echo "qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_28 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_28/bjob_28.sh"

qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_28 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_28/bjob_28.sh

echo "qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_29 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_29/bjob_29.sh"

qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_29 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_29/bjob_29.sh

echo "qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_30 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_30/bjob_30.sh"

qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_30 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_30/bjob_30.sh

echo "qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_31 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_31/bjob_31.sh"

qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_31 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_31/bjob_31.sh

echo "qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_32 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_32/bjob_32.sh"

qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_32 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_32/bjob_32.sh

echo "qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_33 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_33/bjob_33.sh"

qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_33 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_33/bjob_33.sh

echo "qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_34 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_34/bjob_34.sh"

qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_34 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_34/bjob_34.sh

echo "qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_35 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_35/bjob_35.sh"

qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_35 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_35/bjob_35.sh

echo "qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_36 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_36/bjob_36.sh"

qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_36 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_36/bjob_36.sh

echo "qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_37 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_37/bjob_37.sh"

qsub -V -q shortcms -d /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_37 /gwpool/users/ldimatt/scratch0/PHD_MiBi/Summer12_v2/VBFAnalysisPackage/scripts/VBFPreselection/WJetsToLNu_TuneZ2Star_8TeV-madgraph-tarball_ajkumar-SQWaT_PAT_52X_Summer12_v1_PFlow/JOB_37/bjob_37.sh

